### ISSUE TITLE
PHP Parse 에러. (갑자기 일어난 버그라.. 당황해서 일딴 캐시 삭제해봤는데..)

### ISSUE THREAD

**Issue by bjrambo** [poesis/xe-supercache#19]
```
[22-Jan-2017 04:33:34] PHP Parse error:  syntax error, unexpected quoted-string and whitespace (T_ENCAPSED_AND_WHITESPACE) in /home/hosting_users/cafe24_id/www/files/supercache/fullpage_module/1230413/1/module_index/pc_ko_p1.php on line 2
[22-Jan-2017 04:33:34] PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0
[22-Jan-2017 05:07:16] PHP Exception: ParseError #0 "syntax error, unexpected ''a:2:{i:0;i:1485007313;i:1;a:6' (T_ENCAPSED_AND_WHITESPACE)" in files/supercache/fullpage_module/1230413/1/module_index/pc_ko_p1.php on line 2
#0 /home/hosting_users/cafe24_id/www/modules/supercache/supercache.class.php(164): SuperCacheFileDriver->get()
#1 /home/hosting_users/cafe24_id/www/modules/supercache/supercache.model.php(45): SuperCache->getCache()
#2 /home/hosting_users/cafe24_id/www/modules/supercache/supercache.controller.php(864): SuperCacheModel->getFullPageCache()
#3 /home/hosting_users/cafe24_id/www/modules/supercache/supercache.controller.php(75): SuperCacheController->checkFullPageCache()
#4 /home/hosting_users/cafe24_id/www/classes/module/ModuleHandler.class.php(1281): SuperCacheController->triggerBeforeModuleHandlerInit()
#5 /home/hosting_users/cafe24_id/www/classes/module/ModuleHandler.class.php(112): ModuleHandler::triggerCall()
#6 /home/hosting_users/cafe24_id/www/index.php(54): ModuleHandler->__construct()
```
다음과 같은 parse에러가 떠있더라구요.

super캐시를 사용할 비로그인 상태에서는 이런 오류가 뜨고, 해당 오류로 인해 PHP에러가 뜨고 있던 상황이였던것으로 보여집니다.

자체적인 에러가 아닌것 같긴하지만, 혹시나 다른 문제점이 있을 수 있다고 판단하고, 일딴 여기에 오류내용을 남겨봅니다.

**Comment by kijin** [comment]
https://github.com/rhymix/rhymix/pull/532

이 문제와 관련이 있는 것 같네요. 일부 서버 환경에서 용량이 큰 PHP 파일을 갱신한 직후에 인클루드하면 문법 오류가 발생하는 현상입니다. 라이믹스와 슈퍼캐시 양쪽 모두 대응이 되어 있는데, 여전히 어떤 상황에서는 오류가 발생할 수도 있나 봅니다.
